/**
 * Rainbow Preschool – Tailwind CSS Configuration
 * Under Bunnyland Preschool
 *
 * Custom Material Design 3 color tokens, border-radius scale,
 * and font-family definitions for the design system.
 */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002204",
        "on-tertiary-fixed-variant": "#00497d",
        "on-background": "#1e1c00",
        "tertiary-fixed": "#d1e4ff",
        "on-primary-container": "#930015",
        "on-secondary-fixed-variant": "#005313",
        "tertiary": "#0061a4",
        "surface-container": "#f6f0bb",
        "primary-fixed-dim": "#ffb3ae",
        "outline-variant": "#c6c6c6",
        "on-error-container": "#93000a",
        "surface-bright": "#fffadf",
        "primary": "#b81d27",
        "primary-container": "#ffdad7",
        "on-primary": "#ffffff",
        "inverse-primary": "#ffb3ae",
        "background": "#fffadf",
        "on-tertiary-fixed": "#001d36",
        "primary-fixed": "#ffdad7",
        "tertiary-container": "#d1e4ff",
        "surface-variant": "#eae4b1",
        "tertiary-fixed-dim": "#9ecaff",
        "surface-container-lowest": "#ffffff",
        "outline": "#777777",
        "on-primary-fixed-variant": "#930015",
        "on-primary-fixed": "#410004",
        "surface-dim": "#e1dca9",
        "secondary-container": "#94f990",
        "surface-container-high": "#f0eab6",
        "surface-tint": "#b81d27",
        "secondary-fixed-dim": "#78dc77",
        "on-error": "#ffffff",
        "secondary": "#006e1c",
        "on-tertiary-container": "#00497d",
        "on-surface-variant": "#474747",
        "surface-container-low": "#fbf5c1",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-container-highest": "#eae4b1",
        "inverse-surface": "#34310d",
        "inverse-on-surface": "#f8f3be",
        "surface": "#fffadf",
        "secondary-fixed": "#94f990",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#005313",
        "on-surface": "#1e1c00",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Baloo 2"],
        body: ["Poppins"],
        label: ["Poppins"],
      },
    },
  },
};
